version: '3.7'
services:
  app:
    build: ./app
    container_name: plotly-flask
    volumes:
        - ./app/plotly-flask:/app/plotly-flask
    ports:
      - target: 5000
        published: 5001
    environment:
      - API_WORKERS=4     # http://docs.gunicorn.org/en/stable/design.html#how-many-workers
      - API_ACCESSLOG=-   # log connections to stdout inside container
      - API_RELOAD=True   # auto-reload when code changes
      - API_TRACE=True    # enable trace logs for dev
      - FLASK_DEBUG=True
    command: gunicorn -c conf/gunicorn.py app:app
